spring.application.name=usuarios-api

# Spring settings
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.serialization.fail-on-empty-beans=true

spring.jackson.time-zone=GMT-3

spring.datasource.url=jdbc:mysql://localhost:3306/usuarios?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=velsis
spring.datasource.password=velsis
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.minimumidle=4
spring.datasource.hikari.keepaliveTime=15000
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.connectionTimeout=30000 
spring.datasource.hikari.idleTimeout=14400000
spring.datasource.hikari.maxLifetime=28800000 
spring.datasource.hikari.connectionTestQuery=SELECT NOW()

logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.actuator=INFO
logging.level.org.springframework.boot=INFO
logging.level.com.copel=INFO
logging.file.path=/var/logs

spring.main.allow-bean-definition-overriding=true

server.port=8181